Fix view demand screen render and adjust screen to receive an array o…
fga-eps-mds/2020-2-SiGeD-Frontend pull request #52
Opened 2021-04-15 03:50 UTC by yukioz

Fix-view-Screen

# Descrição:

Corrigido a tela de visualizar demanda para exibir um array de objetos do tipo categoria.

2021-04-15 23:14 UTC, JPedroCh submitted a review, later dismissed

2021-04-15 23:14 UTC, JPedroCh commented on src/Pages/ViewDemandsScreen/index.js
>        getUserApi();
Remover essa chamada de função para evitar erro na tela.

2021-04-16 00:49 UTC, GabrielOak submitted a review, later dismissed
Não funciona!

2021-04-16 01:05 UTC, vitorl-s requested changes
Não ta carregando a demanda

2021-04-17 22:06 UTC, vitorl-s approved these changes
Ok!

2021-04-17 23:33 UTC, JPedroCh approved these changes
LGTM!

2021-04-17 23:34 UTC, merged