Criar prontuário dos clientes
fga-eps-mds/2020-2-SiGeD-Frontend pull request #53
Opened 2021-04-15 04:48 UTC by Thiagof99

closes: fga-eps-mds/2020-2-G4#186

## Descrição

Nessa issue  incrementamos a tela de perfil de cliente adicionando o prontuário do cliente

2021-04-16 01:20 UTC, vitorl-s requested changes
Adicionar ícone quando a demanda estiver fechada e arrumar imagem cortando

2021-04-16 22:16 UTC, nYCSTs commented on src/Components/ClientDemandData/index.js
> +          {format(new Date(demand.createdAt), 'dd/MM/yyyy')}
Trocar pela conversão usando o moment, para evitar erro no dia de criação.

2021-04-17 22:26 UTC, vitorl-s approved these changes
Ok!

2021-04-17 23:20 UTC, JPedroCh commented on src/Components/ClientDemandData/index.js
> +          {format(new Date(demand.createdAt), 'dd/MM/yyyy')}
Feito!

2021-04-17 23:21 UTC, nYCSTs approved these changes
Muito bom

2021-04-17 23:23 UTC, merged