CRUD de características
fga-eps-mds/2020-2-SiGeD-Frontend pull request #85
Opened 2021-05-05 01:10 UTC by nYCSTs

**Issue:** resolves fga-eps-mds/2020-2-SiGeD#238
**Issue:** resolves fga-eps-mds/2020-2-SiGeD#239
**Issue:** resolves fga-eps-mds/2020-2-SiGeD#240
**Issue:** resolves fga-eps-mds/2020-2-SiGeD#241
**Issue:** resolves fga-eps-mds/2020-2-SiGeD#242

## Descrição

Adicionada criação, edição e remoção de características.
Adicionada atribuição de características na criação do cliente.

2021-05-12 13:50 UTC, JPedroCh requested changes

2021-05-12 13:50 UTC, JPedroCh commented on src/Pages/ClientProfileScreen/index.js
> +  // Trabalando aki...
Remover comentários desnecessários.

2021-05-12 13:50 UTC, JPedroCh commented on src/Components/SelectedFeatures/Style.js
> +  cursor: pointer;
A cor utilizada para o texto está variando, na tela do prontuário o texto da tag está azul e na tela de características está branco. É melhor padronizar com o texto sendo sempre branco e bold.

2021-05-12 13:50 UTC, JPedroCh commented on src/Components/SelectedFeatures/Style.js
> +  }
Remover @media desnecessário.

2021-05-12 14:56 UTC, nYCSTs commented on src/Components/SelectedFeatures/Style.js
> +  cursor: pointer;
Adicionada cor branca e texto colocado como bold

2021-05-12 14:56 UTC, nYCSTs commented on src/Pages/ClientProfileScreen/index.js
> +  // Trabalando aki...
Removido

2021-05-12 14:56 UTC, nYCSTs commented on src/Components/SelectedFeatures/Style.js
> +  }
Removido

2021-05-12 15:26 UTC, JPedroCh approved these changes
LGTM!

2021-05-18 00:59 UTC, GabrielOak approved these changes
LGTM

2021-05-18 01:01 UTC, merged