Add logo to Navbar
fga-eps-mds/2020-2-SiGeD-Frontend pull request #96
Opened 2021-05-19 00:24 UTC by yukioz

**Issue:** resolves #fga-eps-mds/2020-2-SiGeD/issues/261

## Descrição

Adicionar logo na Navbar do Site.

2021-05-20 23:52 UTC, Thiagof99 requested changes
A logo só foi adicionada na navbar de adiminstradores, adicione também na tela de login e na de profissionais/recepcionistas

2021-05-21 01:33 UTC, EzequielDeOliveira requested changes
Falta um caso onde está escrito o nome "Logo" ao invés da logo

2021-05-21 02:08 UTC, Thiagof99 approved these changes
LGTM!

2021-05-21 02:09 UTC, EzequielDeOliveira approved these changes

2021-05-21 02:09 UTC, merged